name: deploy-caddy
on:
  push:
    paths:
      - 'infra/caddy/**'
    branches: [ master ]
  workflow_dispatch: {}

env:
  VM_HOST:     ${{ vars.VM_HOST }}       # 35.225.153.97
  VM_SSH_USER: ${{ vars.VM_SSH_USER }}   # e.g. borissolomonia

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy caddy files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "35.225.153.97"
          username: "borissolomonia"
          key: ${{ secrets.VM_SSH_KEY }}
          source: "infra/caddy/*"
          target: "/opt/apps/caddy"
          overwrite: true
          strip_components: 2

      - name: Bring up Caddy and reload
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "35.225.153.97"
          username: "borissolomonia"
          key: ${{secrets.VM_SSH_KEY}}
          script: |
            set -euo pipefail
            sudo docker network create web 2>/dev/null || true
            cd /opt/apps/caddy
            sudo docker compose up -d
            # if already running, just reload config
            sudo docker compose exec caddy caddy reload --config /etc/caddy/Caddyfile || true
            curl -fsS http://127.0.0.1/health
